spring.application.name=carebridge-rag-service

server.port=${PORT:8081}

# OpenRouter
openrouter.api.key=${OPENROUTER_API_KEY}
ai.model=${AI_MODEL:openai/gpt-4o-mini}
embedding.model=${EMBEDDING_MODEL:text-embedding-3-small}

# Qdrant
qdrant.url=${QDRANT_URL}
qdrant.api.key=${QDRANT_API_KEY}
qdrant.collection=${QDRANT_COLLECTION:carebridge}




logging.level.root=INFO